version: '3'
services:
  web:
    build: .
    image: 'gds-prototyping-kit:latest'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
